CREATE ROLE admin LOGIN PASSWORD 'admin_pass';
CREATE ROLE etl_user LOGIN PASSWORD 'etl_pass';
CREATE ROLE analyst LOGIN PASSWORD 'analyst_pass';

-- صلاحيات admin
GRANT ALL PRIVILEGES ON DATABASE dwh TO admin;

-- صلاحيات ETL
GRANT USAGE ON SCHEMA raw TO etl_user;
GRANT USAGE ON SCHEMA dv TO etl_user;
GRANT USAGE ON SCHEMA dm TO etl_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA raw TO etl_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dv TO etl_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dm TO etl_user;

-- analyst: قراءة فقط
GRANT USAGE ON SCHEMA dm TO analyst;
GRANT SELECT ON ALL TABLES IN SCHEMA dm TO analyst;